/* Football Score App UI enhancements. */
function betFirstKickoff(b){var times=[];(b.legs||[]).forEach(function(l){var g=legGame(l,b);if(g&&g.date)times.push(Date.parse(g.date)||0);else ['eventStart','startTime','gameDate','eventDate'].some(function(k){var t=Date.parse(l[k]||0)||0;if(t){times.push(t);return true}return false})});var g=findGame(b);if(g&&g.date)times.push(Date.parse(g.date)||0);times=times.filter(Boolean);return times.length?Math.min.apply(null,times):(Date.parse(b.acceptedDate||0)||0)}
function sortBets(a,b){var sa=stateOrder(a),sb=stateOrder(b);if(sa!==sb)return sa-sb;return betFirstKickoff(a)-betFirstKickoff(b)}
function gameNetwork(g){var out=[];(comp(g).broadcasts||[]).forEach(function(b){(b.names||[]).forEach(function(n){if(n&&out.indexOf(n)<0)out.push(n)})});return out.join(' / ')}
function pacificKickoff(g){if(!g||!g.date)return '';try{return new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',weekday:'short',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(g.date))}catch(e){return ''}}
function enhancedGameDetail(g){if(!g)return '';if(gs(g)!=='pre')return gameDetail(g);return [pacificKickoff(g),gameNetwork(g)].filter(Boolean).join(' · ')}
function isPlayerProp(x){if(!x)return false;if(x.market==='player_prop')return true;var s=[x.description,x.selection,x.raw,x.rawWager].filter(Boolean).join(' ').toLowerCase();return /\b(anytime|touchdown|td scorer|receptions?|receiving|rushing|passing|yards?|completions?|attempts?|interceptions?|sacks?|carries|longest|player)\b/.test(s)&&!/\b(team total|game total)\b/.test(s)}
function displayBetType(b){if(b.structure==='teaser')return'teaser';if(b.structure==='parlay')return'parlay';if(isPlayerProp(b))return'prop';return String(b.structure||'straight').replace(/_/g,' ')}
function pickIsAway(item,t){if(t&&t.away&&teamMatches(t.away,item.selection))return true;if(t&&t.home&&teamMatches(t.home,item.selection))return false;var s=String(item.selection||item.description||item.raw||item.rawWager||'').toLowerCase();return item.awayTeam&&s.indexOf(String(item.awayTeam).toLowerCase())>=0}
function compactBetLine(item,g,sp){if(!item.awayTeam||!item.homeTeam)return esc(item.description||item.selection||item.raw||item.rawWager||'Wager');var t=g?teams(g):{},away=betTeamHtml(t.away,item.awayTeam,sp),home=betTeamHtml(t.home,item.homeTeam,sp),line=item.line!=null?Number(item.line):null;if(item.market==='spread'||item.market==='moneyline'||item.market==='ml'){var pa=pickIsAway(item,t),pick=pa?away:home,opp=pa?home:away;var n=(item.market==='spread'&&line!=null&&line!==0)?' '+(line>0?'+':'')+line:'';return'<span class="compact-pick">'+pick+n+' <span class="pick-word">over</span> '+opp+'</span>'}if(item.market==='total')return'<span class="compact-pick">'+away+' <span class="pick-word">vs</span> '+home+' · '+esc(item.selection||'Total')+(line!=null?' '+line:'')+'</span>';return'<span class="compact-pick">'+away+' <span class="pick-word">at</span> '+home+'</span>'}
function legGame(leg,parent){var sp=leg.sport||parent.sport||'College',pool=eventPoolForSport(sp);if(leg.espnEventId){var byId=pool.find(function(e){return String(e.id)===String(leg.espnEventId)});if(byId)return byId}if(leg.awayTeam&&leg.homeTeam)return pool.find(function(e){return gameMatches(e,leg)})||null;return null}
function legKickoff(l,b){var g=legGame(l,b);if(g&&g.date)return Date.parse(g.date)||0;var keys=['eventStart','startTime','gameDate','eventDate'];for(var i=0;i<keys.length;i++){var t=Date.parse(l[keys[i]]||0)||0;if(t)return t}return 0}
function sortedLegs(b){return(b.legs||[]).map(function(l,i){return{l:l,i:i,t:legKickoff(l,b)}}).sort(function(a,z){if(a.t&&z.t&&a.t!==z.t)return a.t-z.t;if(a.t&&!z.t)return-1;if(!a.t&&z.t)return 1;return a.i-z.i}).map(function(x){return x.l})}
function legHtml(l,b){var st=legDisplayStatus(l,b),g=legGame(l,b),h=itemHealth(l,g),prop=isPlayerProp(l),pe=prop?propEval(l,g):null,stat=pe&&pe.value!=null?' · '+pe.value+(pe.target!=null?' / '+pe.target:''):'';var label=st==='won'?'Won':st==='lost'?'Lost':st==='push'?'Push':st==='live'?'Live':'Upcoming';h=st==='won'?5:st==='lost'?1:st==='push'?null:h;var primary=compactBetLine(l,g,l.sport||b.sport),propLine=prop?'<div class="leg-prop">'+esc(l.description||l.selection||l.raw||'Prop')+'</div>':'';var meta=[shortScore(g),g?enhancedGameDetail(g):'Upcoming'].filter(Boolean).join(' · '),eid=l.espnEventId||(g&&g.id)||b.espnEventId;return'<div class="leg"><div><div class="legmain">'+primary+'</div>'+propLine+'<div class="legsub">'+esc(meta)+stat+'</div>'+gamecastLink(l.sport||b.sport,eid)+'</div><div class="status-pack">'+healthHtml(h)+'<span class="legstatus '+st+'">'+label+'</span></div></div>'}
function betCard(b){var g=findGame(b),gid=g?String(g.id):betGameId(b),prop=isPlayerProp(b),hasLegs=Array.isArray(b.legs)&&b.legs.length,id='m'+String(b.betId).replace(/[^a-zA-Z0-9]/g,''),legsId='l'+String(b.betId).replace(/[^a-zA-Z0-9]/g,'');var money=b.risk!=null?'$'+Number(b.risk).toFixed(0)+(b.toWin!=null?' → $'+Number(b.toWin).toFixed(2):''):'',scoreText=g?enhancedGameDetail(g):(hasLegs?'View linked games':'No ESPN match yet');var closedResult=authoritativeResult(b)||parlayAutoResult(b)||result(b,g),health=closedResult==='won'?5:closedResult==='lost'?1:closedResult?null:hasLegs?parlayHealth(b):itemHealth(b,g);var title=hasLegs?esc(b.structure==='teaser'?'Teaser':b.structure==='parlay'?'Parlay':'Wager'):b.awayTeam&&b.homeTeam?compactBetLine(b,g,b.sport):esc(b.description||b.selection||'Wager');var propLine=!hasLegs&&prop?'<div class="pick">'+esc(b.description||b.selection||b.raw||b.rawWager||'Prop')+'</div>':(!hasLegs&&b.awayTeam&&b.homeTeam?'':'<div class="pick">'+fmtPick(b)+'</div>'),eid=b.espnEventId||(g&&g.id);return'<div class="card '+(betState(b,g)==='live'?'live':'')+'" data-gameid="'+gid+'"><div class="top"><div><b>'+title+'</b><div class="sub">'+(b.sport||'Other')+' · '+displayBetType(b)+'</div></div><div class="status-pack">'+healthHtml(health)+'<button class="status-button" aria-label="Change wager status" onclick="toggleM(\''+id+'\')">'+pill(b,g)+'</button></div></div>'+propLine+(money?'<div class="money">'+money+'</div>':'')+liveBetContext(g)+'<div class="game-clock-row">'+(gid?'<div class="scorelink" onclick="goToGame(\''+gid+'\')">'+scoreText+'</div>':'<div class="scorelink">'+scoreText+'</div>')+gamecastLink(b.sport,eid)+'</div>'+(hasLegs?'<button class="expand" onclick="toggleLegs(\''+legsId+'\')">Show '+b.legs.length+' legs</button><div class="legs" id="'+legsId+'">'+sortedLegs(b).map(function(l){return legHtml(l,b)}).join('')+'</div>':'')+'<div class="manual" id="'+id+'"><button onclick="setOv(\''+b.betId+'\',\'won\')">Won</button><button onclick="setOv(\''+b.betId+'\',\'lost\')">Lost</button><button onclick="setOv(\''+b.betId+'\',\'push\')">Push</button><button onclick="setOv(\''+b.betId+'\',\'auto\')">Auto</button></div></div>'}
/* Override scoreboard game detail so scheduled games show Pacific kickoff + ESPN network. Live/final behavior remains unchanged. */
function gameClock(e){if(gs(e)==='pre')return enhancedGameDetail(e);var st=comp(e).status||e.status||{},detail=gameDetail(e);if(gs(e)!=='in'||/half|end|delay|suspend/i.test(detail))return detail;var clock=st.displayClock,p=Number(st.period);return clock?'LIVE · '+clock+(p?' · '+(p>4?'OT':'Q'+p):''):detail||'Live · clock unavailable'}
var baseRenderBets=renderBets;
renderBets=function(){
  baseRenderBets();
  var selected=S.bets.filter(function(b){return betSport==='all'||(betSport==='nfl'?b.sport==='NFL':b.sport==='College')}),w=0,l=0,p=0,pl=0,risk=0,possible=0,open=0;
  selected.forEach(function(b){var r=authoritativeResult(b)||parlayAutoResult(b)||result(b,findGame(b));if(r==='won'){w++;pl+=profit(b)}else if(r==='lost'){l++;pl-=Number(b.risk||0)}else if(r==='push')p++;else{open++;risk+=Number(b.risk||0);possible+=Number(b.toWin||0)}});
  var s=document.querySelector('#bets .summary');if(!s)return;
  s.innerHTML='<div class="summary-left"><div class="sum summary-row"><b>'+selected.length+' bets · '+w+'-'+l+'-'+p+'</b></div><div class="sum summary-row"><b>'+open+' open · $'+risk.toFixed(0)+' at risk to win $'+possible.toFixed(0)+'</b></div></div><div class="sum summary-pl '+(pl>=0?'plpos':'plneg')+'"><b>'+(pl>=0?'+':'')+'$'+pl.toFixed(0)+'</b><span>P/L</span></div>';
};
var enhancementStyle=document.createElement('style');enhancementStyle.textContent='.scorelink{text-decoration:none;font-size:13px;color:#b8d4e8}.situation{font-size:13px;font-weight:400;color:#b8d4e8}.game-clock-row .state{font-size:13px;color:#b8d4e8}.compact-pick{display:inline-flex;flex-wrap:wrap;align-items:center;gap:5px}.compact-pick .bet-team{font-weight:800}.pick-word{font-weight:500;color:var(--muted);font-size:11px}.leg-prop{font-size:12px;font-weight:800;margin-top:4px}.gamecast:hover{text-decoration:none}#bets .summary{display:grid;grid-template-columns:minmax(0,3fr) minmax(92px,1fr);grid-template-rows:1fr 1fr;gap:7px}.summary-left{display:contents}.summary-row{grid-column:1;display:flex;align-items:center;white-space:nowrap;overflow:hidden;padding:10px 12px}.summary-left .summary-row:first-child{grid-row:1}.summary-left .summary-row:last-child{grid-row:2}.summary-pl{grid-column:2;grid-row:1/3;display:flex!important;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:10px 8px!important}.summary-pl b{font-size:26px;line-height:1}.summary-pl span{font-size:11px;margin-top:7px;font-weight:700;letter-spacing:.6px}.summary-row b{font-size:15px}@media(max-width:390px){#bets .summary{grid-template-columns:minmax(0,3.25fr) minmax(82px,1fr);gap:6px}.summary-row{padding:9px 8px}.summary-row b{font-size:14px}.summary-left .summary-row:last-child b{font-size:12.5px;letter-spacing:-.35px}.summary-pl b{font-size:22px}}';document.head.appendChild(enhancementStyle);renderAll();
